package ExceptionDemos;

public class ExceptionDemo3 {
    public static void main(String[] args) {
        //异常作用2：异常可以作为方法内部的一种特殊返回值，以便通知调用这底层的执行情况
        Student s1 = new Student();
        s1.setAge(100);



    }
}
